spring:
  datasource:
    url: jdbc:mysql://shineeds-db-instance.cghfkoj2aznr.ap-northeast-2.rds.amazonaws.com:3306/shyneeds?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    username: shineeds
    password: fast1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

